### ISSUE TITLE
how to eval a lazy call in the lazily called caller's env

### ISSUE THREAD

**Issue by JeffreySarnoff** [bramtayl/LazyCall.jl#5]

**Comment by bramtayl** [comment]
I'm not sure what you mean. Can you give an example?

**Comment by JeffreySarnoff** [comment]
back when R, I organized a special purpose exception resolver that would be called from the relevant context and in pursuing a way to resolve the exception would call subordinate supporting capabilities and they in turn might call sub-sub-supports.  The processing would not necessarily return up -- sometimes it would seek to end the outer context from wherever sub-place it happend to be when reaching that conclusion.  So, I always needed `eval in calller's context` and often needed `eval in the context of caller's caller` and sometimes needed `eval in the third outermost context`.

**Comment by JeffreySarnoff** [comment]
(that was for the other Lazy -- for this one I want to save for later use a function with predermined args [at least some of them] where one of those predtermined args is itself a LazyCall.

**Comment by bramtayl** [comment]
Hmm, I'm not sure exactly what you mean, but it is definitely possible to put a LazyCall inside a LazyCall.

```julia
A = [1, 2]
B = [2, 3]
C = [3, 4]
result = @unweave vcat( ~( @unweave vcat(~A, ~B) ), ~C)
```

**Comment by JeffreySarnoff** [comment]
Will the same thing that causes the outer lazy call to happen always then cause the inner call to happen .. or is there a way to let the inner lazy call be lazier still?

**Comment by JeffreySarnoff** [comment]
Here is a better example --
I have written RollingFunctions.jl and some exports accept customized weighting for the successive observations within each  windowed roll prior to advancing the window over the data.   Usually, custom weights are selected and kept unchanged, reused from time to time. CouldI have each of a half-dozen specific weightings separately wrapped up with lazy calling of the same function .. and if so, would their be a dispatch-driven way to later select which lazy wrap got called.?

**Comment by bramtayl** [comment]
Hmm. I guess I'm still confused. Here's a continuation of the example above:

```julia
using LazyCall
A = [1, 2]
B = [3, 4]
C = [5, 6]
result = @unweave vcat( ~( @unweave vcat(~A, ~B) ), ~C)

Base.broadcast(result.positional[1], Base.broadcast(result.positional[2]), result.positional[3] )
Base.broadcast(result)
```

**Comment by bramtayl** [comment]
If you wanted to recur broadcast over the nested lazycalls, you could do something like this: 

```julia
my_recur(a) = a
my_recur(l::LazyCall.Call) = my_broadcast(l)

my_broadcast(l) = begin 
    new_positional = map(my_recur, l.positional)
    LazyCall.Call(new_positional, l.keyword) |> broadcast
end

my_broadcast(result)
```
